name: Release

on:
  push:
    tags:
      - 'v*' # Trigger workflow on tags matching the pattern v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Set up cross-compiler for ARM64
        if: matrix.arch == 'arm64' && runner.os == 'Linux'
        run: sudo apt install -y gcc-aarch64-linux-gnu

      - name: Build binary
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            export CC=gcc
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              export CC=aarch64-linux-gnu-gcc
            fi
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            export CC=clang
          fi
          $CC main.c -o song-starter-${{ runner.os | toLower }}-${{ matrix.arch }}

      - name: Upload binary to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: song-starter-${{ runner.os | toLower }}-${{ matrix.arch }}
          path: song-starter-${{ runner.os | toLower }}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/song-starter-*
