name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C compiler
        run: sudo apt-get install build-essential

      - name: Build the CLI
        run: |
          gcc -o song-starter main.c

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automatic release for version ${{ github.ref_name }}.
          draft: false
          prerelease: false

      - name: Package binary
        run: |
          mkdir -p dist
          mv song-starter dist/

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/song-starter
          asset_name: song-starter
          asset_content_type: application/octet-stream
