name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on tags matching the pattern v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt update
            sudo apt install -y build-essential
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              sudo apt install -y gcc-aarch64-linux-gnu
            fi
          fi

      - name: Build binary
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            export OS_NAME="linux"
            export CC=gcc
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              export CC=aarch64-linux-gnu-gcc
            fi
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            export OS_NAME="osx"
            export CC=clang
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              export CFLAGS="-target arm64-apple-macos11"
            elif [[ "${{ matrix.arch }}" == "x86_64" ]]; then
              export CFLAGS="-arch x86_64"
            fi
          fi
          $CC $CFLAGS src/main.c -o song-starter-${OS_NAME}-${{ matrix.arch }}

      - name: Upload binary to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: song-starter-${OS_NAME}-${{ matrix.arch }}
          path: song-starter-${OS_NAME}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload release assets
        run: |
          for binary in ./artifacts/song-starter-*; do
            arch=$(basename $binary | cut -d- -f3-)
            renamed_binary="./artifacts/song-starter-$arch"
            mv "$binary" "$renamed_binary"
            echo "Uploading $renamed_binary"
            gh release upload "${{ github.ref_name }}" "$renamed_binary" --clobber
          done
